import 'package:flutter/material.dart';
import 'package:adiccion/widget/user.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Buscador(),
        ]),
      ),
    );
  }
}

class Buscador extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFF0FFFD)),
          child: Stack(
            children: [
              Positioned(
                left: -2,
                top: 0,
                child: Container(
                  width: 393,
                  height: 112,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 393,
                          height: 112,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 3.13,
                                color: const Color(0xFF23B0BD),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 12.76,
                        top: 9.21,
                        child: SizedBox(
                          width: 162.90,
                          height: 28.45,
                          child: Text(
                            'Step by Step',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 24,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w800,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 19.58,
                        top: 88.29,
                        child: Container(
                          width: 53.59,
                          height: 16.11,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(78.20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 30.19,
                        top: 90.61,
                        child: SizedBox(
                          width: 32.63,
                          height: 11.77,
                          child: Text(
                            'Todos',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 10,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 96,
                        top: 88.29,
                        child: Container(
                          width: 81.66,
                          height: 16.11,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFC6FAF6),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(78.20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 111.50,
                        top: 89.87,
                        child: SizedBox(
                          width: 52.51,
                          height: 11.77,
                          child: Text(
                            'No leídos',
                            style: TextStyle(
                              color: const Color(0xFF1E1E1E),
                              fontSize: 10,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 199.34,
                        top: 88.29,
                        child: Container(
                          width: 81.66,
                          height: 16.11,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFC6FAF6),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 3.13,
                                color: const Color(0xFFC6FAF6),
                              ),
                              borderRadius: BorderRadius.circular(78.20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 212.93,
                        top: 89.87,
                        child: SizedBox(
                          width: 52.51,
                          height: 11.77,
                          child: Text(
                            'Favoritos',
                            style: TextStyle(
                              color: const Color(0xFF1E1E1E),
                              fontSize: 10,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 300.23,
                        top: 88.29,
                        child: Container(
                          width: 81.66,
                          height: 16.11,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFC6FAF6),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 3.13,
                                color: const Color(0xFFC6FAF6),
                              ),
                              borderRadius: BorderRadius.circular(78.20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 313.91,
                        top: 89.82,
                        child: SizedBox(
                          width: 52.51,
                          height: 11.77,
                          child: Text(
                            'Grupos 1',
                            style: TextStyle(
                              color: const Color(0xFF1E1E1E),
                              fontSize: 10,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 309.58,
                        top: 9,
                        child: Container(
                          width: 42.53,
                          height: 30.62,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/43x31"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 352.11,
                        top: 9,
                        child: Container(
                          width: 29.77,
                          height: 30.62,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/30x31"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 8.70,
                        top: 45.37,
                        child: Container(
                          width: 377.85,
                          height: 30.41,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFDAFFFC),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFFDAFFFC),
                              ),
                              borderRadius: BorderRadius.circular(25),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 22.11,
                        top: 49,
                        child: Container(
                          width: 24.48,
                          height: 24.48,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/24x24"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 60.64,
                        top: 52.15,
                        child: SizedBox(
                          width: 50.97,
                          height: 16.68,
                          child: Text(
                            'Buscar',
                            style: TextStyle(
                              color: const Color(0xFF1E1E1E),
                              fontSize: 15,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),

Positioned(
  left: 0,
  top: 120,
  child: Container(
    width: 393,
    height: 72,
    child: AvatarBlock(),
  ),
),

Positioned(
  left: 0,
  top: 200,
  child: Container(
    width: 393,
    height: 72,
    child: AvatarBlock(),
  ),
),

Positioned(
  left: 0,
  top: 280,
  child: Container(
    width: 393,
    height: 72,
    child: AvatarBlock(),
  ),
),
Positioned(
  left: 0,
  top: 360,
  child: Container(
    width: 393,
    height: 72,
    child: AvatarBlock(),
  ),
),
Positioned(
  left: 0,
  top: 440,
  child: Container(
    width: 393,
    height: 72,
    child: AvatarBlock(),
  ),
),
Positioned(
  left: 0,
  top: 520,
  child: Container(
    width: 393,
    height: 72,
    child: AvatarBlock(),
  ),
),
Positioned(
  left: 0,
  top: 600,
  child: Container(
    width: 393,
    height: 72,
    child: AvatarBlock(),
  ),
),
Positioned(
  left: 0,
  top: 680,
  child: Container(
    width: 393,
    height: 72,
    child: AvatarBlock(),
  ),
),


              Positioned(
                left: 0,
                top: 760,
                child: Container(
                  width: 393,
                  height: 84,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0.50,
                        child: Container(
                          width: 393,
                          height: 83,
                          decoration: BoxDecoration(color: const Color(0xFFFAFAFA)),
                        ),
                      ),
                      Positioned(
                        left: 129,
                        top: 69.50,
                        child: Container(
                          width: 134,
                          height: 5,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 27,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 103,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 179,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF08C9DB),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 254,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 330,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 393,
                          height: 0.50,
                          decoration: BoxDecoration(color: const Color(0xFFBDC5CD)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}