import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Buscador(),
        ]),
      ),
    );
  }
}

class Buscador extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFF0FFFD)),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 375,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 30,
                top: 11,
                child: Text(
                  '9:41',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Roboto',
                    fontWeight: FontWeight.w500,
                    height: 1.43,
                    letterSpacing: 0.14,
                  ),
                ),
              ),
              Positioned(
                left: 81,
                top: 0,
                child: Container(
                  width: 214,
                  height: 35,
                  decoration: ShapeDecoration(
                    color: Colors.black,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 54,
                child: Container(
                  width: 393,
                  height: 112,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 393,
                          height: 112,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 3.13,
                                color: const Color(0xFF23B0BD),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 12.76,
                        top: 9.21,
                        child: SizedBox(
                          width: 162.90,
                          height: 28.45,
                          child: Text(
                            'Step by Step',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 24,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w800,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 19.58,
                        top: 88.29,
                        child: Container(
                          width: 53.59,
                          height: 16.11,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(78.20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 30.19,
                        top: 90.61,
                        child: SizedBox(
                          width: 32.63,
                          height: 11.77,
                          child: Text(
                            'Todos',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 10,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 96,
                        top: 88.29,
                        child: Container(
                          width: 81.66,
                          height: 16.11,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFC6FAF6),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(78.20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 111.50,
                        top: 89.87,
                        child: SizedBox(
                          width: 52.51,
                          height: 11.77,
                          child: Text(
                            'No leídos',
                            style: TextStyle(
                              color: const Color(0xFF1E1E1E),
                              fontSize: 10,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 199.34,
                        top: 88.29,
                        child: Container(
                          width: 81.66,
                          height: 16.11,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFC6FAF6),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 3.13,
                                color: const Color(0xFFC6FAF6),
                              ),
                              borderRadius: BorderRadius.circular(78.20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 212.93,
                        top: 89.87,
                        child: SizedBox(
                          width: 52.51,
                          height: 11.77,
                          child: Text(
                            'Favoritos',
                            style: TextStyle(
                              color: const Color(0xFF1E1E1E),
                              fontSize: 10,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 300.23,
                        top: 88.29,
                        child: Container(
                          width: 81.66,
                          height: 16.11,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFC6FAF6),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 3.13,
                                color: const Color(0xFFC6FAF6),
                              ),
                              borderRadius: BorderRadius.circular(78.20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 313.91,
                        top: 89.82,
                        child: SizedBox(
                          width: 52.51,
                          height: 11.77,
                          child: Text(
                            'Grupos 1',
                            style: TextStyle(
                              color: const Color(0xFF1E1E1E),
                              fontSize: 10,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 309.58,
                        top: 9,
                        child: Container(
                          width: 42.53,
                          height: 30.62,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://cdn-icons-png.flaticon.com/512/1260/1260254.png"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 352.11,
                        top: 9,
                        child: Container(
                          width: 29.77,
                          height: 30.62,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://cdn-icons-png.flaticon.com/512/61/61140.png"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 8.70,
                        top: 45.37,
                        child: Container(
                          width: 377.85,
                          height: 30.41,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFDAFFFC),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFFDAFFFC),
                              ),
                              borderRadius: BorderRadius.circular(25),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 22.11,
                        top: 49,
                        child: Container(
                          width: 24.48,
                          height: 24.48,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://cdn-icons-png.flaticon.com/512/3721/3721746.png"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 60.64,
                        top: 52.15,
                        child: SizedBox(
                          width: 50.97,
                          height: 16.68,
                          child: Text(
                            'Buscar',
                            style: TextStyle(
                              color: const Color(0xFF1E1E1E),
                              fontSize: 15,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 176,
                child: Container(
                  width: 393,
                  height: 72,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 12,
                    children: [
                      Container(
                        width: 40,
                        height: 40,
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(9999),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 40,
                                height: 40,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://cdn-icons-png.flaticon.com/512/12225/12225881.png"),
                                    fit: BoxFit.cover,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 2,
                          children: [
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Marta Lucia',
                                style: TextStyle(
                                  color: const Color(0xFF757575) /* Text-Default-Secondary */,
                                  fontSize: 16,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w600,
                                  height: 1.40,
                                ),
                              ),
                            ),
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Adicta al alcohol desde hace 9 meses',
                                style: TextStyle(
                                  color: const Color(0xFFB3B3B3) /* Text-Default-Tertiary */,
                                  fontSize: 14,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 1.40,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 258,
                child: Container(
                  width: 393,
                  height: 72,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 12,
                    children: [
                      Container(
                        width: 40,
                        height: 40,
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(9999),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 40,
                                height: 40,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://cdn-icons-png.flaticon.com/512/12225/12225881.png"),
                                    fit: BoxFit.cover,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 2,
                          children: [
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Marta Lucia',
                                style: TextStyle(
                                  color: const Color(0xFF757575) /* Text-Default-Secondary */,
                                  fontSize: 16,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w600,
                                  height: 1.40,
                                ),
                              ),
                            ),
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Adicta al alcohol desde hace 9 meses',
                                style: TextStyle(
                                  color: const Color(0xFFB3B3B3) /* Text-Default-Tertiary */,
                                  fontSize: 14,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 1.40,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 340,
                child: Container(
                  width: 393,
                  height: 72,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 12,
                    children: [
                      Container(
                        width: 40,
                        height: 40,
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(9999),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 40,
                                height: 40,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://cdn-icons-png.flaticon.com/512/12225/12225881.png"),
                                    fit: BoxFit.cover,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 2,
                          children: [
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Marta Lucia',
                                style: TextStyle(
                                  color: const Color(0xFF757575) /* Text-Default-Secondary */,
                                  fontSize: 16,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w600,
                                  height: 1.40,
                                ),
                              ),
                            ),
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Adicta al alcohol desde hace 9 meses',
                                style: TextStyle(
                                  color: const Color(0xFFB3B3B3) /* Text-Default-Tertiary */,
                                  fontSize: 14,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 1.40,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 422,
                child: Container(
                  width: 393,
                  height: 72,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 12,
                    children: [
                      Container(
                        width: 40,
                        height: 40,
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(9999),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 40,
                                height: 40,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://cdn-icons-png.flaticon.com/512/12225/12225881.png"),
                                    fit: BoxFit.cover,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 2,
                          children: [
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Marta Lucia',
                                style: TextStyle(
                                  color: const Color(0xFF757575) /* Text-Default-Secondary */,
                                  fontSize: 16,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w600,
                                  height: 1.40,
                                ),
                              ),
                            ),
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Adicta al alcohol desde hace 9 meses',
                                style: TextStyle(
                                  color: const Color(0xFFB3B3B3) /* Text-Default-Tertiary */,
                                  fontSize: 14,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 1.40,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 504,
                child: Container(
                  width: 393,
                  height: 72,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 12,
                    children: [
                      Container(
                        width: 40,
                        height: 40,
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(9999),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 40,
                                height: 40,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://cdn-icons-png.flaticon.com/512/12225/12225881.png"),
                                    fit: BoxFit.cover,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 2,
                          children: [
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Marta Lucia',
                                style: TextStyle(
                                  color: const Color(0xFF757575) /* Text-Default-Secondary */,
                                  fontSize: 16,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w600,
                                  height: 1.40,
                                ),
                              ),
                            ),
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Adicta al alcohol desde hace 9 meses',
                                style: TextStyle(
                                  color: const Color(0xFFB3B3B3) /* Text-Default-Tertiary */,
                                  fontSize: 14,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 1.40,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 586,
                child: Container(
                  width: 393,
                  height: 72,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 12,
                    children: [
                      Container(
                        width: 40,
                        height: 40,
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(9999),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 40,
                                height: 40,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://cdn-icons-png.flaticon.com/512/12225/12225881.png"),
                                    fit: BoxFit.cover,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 2,
                          children: [
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Marta Lucia',
                                style: TextStyle(
                                  color: const Color(0xFF757575) /* Text-Default-Secondary */,
                                  fontSize: 16,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w600,
                                  height: 1.40,
                                ),
                              ),
                            ),
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Adicta al alcohol desde hace 9 meses',
                                style: TextStyle(
                                  color: const Color(0xFFB3B3B3) /* Text-Default-Tertiary */,
                                  fontSize: 14,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 1.40,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 668,
                child: Container(
                  width: 393,
                  height: 82,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 12,
                    children: [
                      Container(
                        width: 40,
                        height: 40,
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(9999),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 40,
                                height: 40,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://cdn-icons-png.flaticon.com/512/12225/12225881.png"),
                                    fit: BoxFit.cover,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 2,
                          children: [
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Marta Lucia',
                                style: TextStyle(
                                  color: const Color(0xFF757575) /* Text-Default-Secondary */,
                                  fontSize: 16,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w600,
                                  height: 1.40,
                                ),
                              ),
                            ),
                            SizedBox(
                              width: 309,
                              child: Text(
                                'Adicta al alcohol desde hace 9 meses',
                                style: TextStyle(
                                  color: const Color(0xFFB3B3B3) /* Text-Default-Tertiary */,
                                  fontSize: 14,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 1.40,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 760,
                child: Container(
                  width: 393,
                  height: 84,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0.50,
                        child: Container(
                          width: 393,
                          height: 83,
                          decoration: BoxDecoration(color: const Color(0xFFFAFAFA)),
                        ),
                      ),
                      Positioned(
                        left: 129,
                        top: 69.50,
                        child: Container(
                          width: 134,
                          height: 5,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 27,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 103,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 179,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF08C9DB),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 254,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 330,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 393,
                          height: 0.50,
                          decoration: BoxDecoration(color: const Color(0xFFBDC5CD)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}