import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Consultas(),
        ]),
      ),
    );
  }
}

class Consultas extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFF0FFFD)),
          child: Stack(
            children: [
              Positioned(
                left: 16,
                top: 68,
                child: Container(
                  width: 343,
                  height: 36,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 307,
                        top: 8,
                        child: Text(
                          'Next',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: const Color(0xFF23B0BD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 82,
                        top: 0,
                        child: Text(
                          'CONSULTAS',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 30,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 8,
                        child: Text(
                          'Back',
                          style: TextStyle(
                            color: const Color(0xFF23B0BD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 737,
                child: Container(
                  width: 375,
                  height: 83.50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0.50,
                        child: Container(
                          width: 375,
                          height: 83,
                          decoration: BoxDecoration(color: const Color(0xFFFAFAFA)),
                        ),
                      ),
                      Positioned(
                        left: 120,
                        top: 69.50,
                        child: Container(
                          width: 134,
                          height: 5,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 98,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 170,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 242,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 314,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 375,
                          height: 0.50,
                          decoration: BoxDecoration(color: const Color(0xFFBDC5CD)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 136,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 15,
                        child: Text(
                          'PRESENCIALES',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF4B9360),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 329,
                        top: 18,
                        child: Container(
                          width: 12,
                          height: 12,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 184,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 16,
                        child: Text(
                          'VIRTUALES',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFFBDBDBD),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 232,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 15,
                        child: Text(
                          'CONYUGAALES\n',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF4B9360),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 329,
                        top: 18,
                        child: Container(
                          width: 12,
                          height: 12,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 280,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 16,
                        child: Text(
                          'Radio option here...',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFFBDBDBD),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 328,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 16,
                        child: Text(
                          'Radio option here...',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFFBDBDBD),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 376,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 15,
                        child: Text(
                          'Radio option here...',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF4B9360),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 329,
                        top: 18,
                        child: Container(
                          width: 12,
                          height: 12,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 670,
                child: Container(
                  width: 343,
                  padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF23B0BD),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 12,
                    children: [
                      Text(
                        'I love it!',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 68,
                child: Container(
                  width: 343,
                  height: 36,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 307,
                        top: 8,
                        child: Text(
                          'Next',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: const Color(0xFF23B0BD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 82,
                        top: 0,
                        child: Text(
                          'CONSULTAS',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 30,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 8,
                        child: Text(
                          'Back',
                          style: TextStyle(
                            color: const Color(0xFF23B0BD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 737,
                child: Container(
                  width: 375,
                  height: 83.50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0.50,
                        child: Container(
                          width: 375,
                          height: 83,
                          decoration: BoxDecoration(color: const Color(0xFFFAFAFA)),
                        ),
                      ),
                      Positioned(
                        left: 120,
                        top: 69.50,
                        child: Container(
                          width: 134,
                          height: 5,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 98,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 170,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 242,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE7E7E7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 314,
                        top: 15,
                        child: Container(
                          width: 32,
                          height: 32,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 375,
                          height: 0.50,
                          decoration: BoxDecoration(color: const Color(0xFFBDC5CD)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 136,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 15,
                        child: Text(
                          'PRESENCIALES',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF4B9360),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 329,
                        top: 18,
                        child: Container(
                          width: 12,
                          height: 12,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 184,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 16,
                        child: Text(
                          'VIRTUALES',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFFBDBDBD),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 232,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 15,
                        child: Text(
                          'CONYUGAALES\n',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF4B9360),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 329,
                        top: 18,
                        child: Container(
                          width: 12,
                          height: 12,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 280,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 16,
                        child: Text(
                          'Radio option here...',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFFBDBDBD),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 328,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 16,
                        child: Text(
                          'Radio option here...',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFFBDBDBD),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 376,
                child: Container(
                  width: 343,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 15,
                        child: Text(
                          'Radio option here...',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 49,
                        child: Container(
                          width: 343,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7E7E7),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 327,
                        top: 16,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: ShapeDecoration(
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF4B9360),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 329,
                        top: 18,
                        child: Container(
                          width: 12,
                          height: 12,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF23B0BD),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 670,
                child: Container(
                  width: 343,
                  padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF23B0BD),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 12,
                    children: [
                      Text(
                        'I love it!',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}