import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Menu(),
        ]),
      ),
    );
  }
}

class Menu extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFF0FFFD)),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            spacing: 10,
            children: [
              Container(
                width: 393,
                height: 852,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 393,
                        height: 107,
                        decoration: BoxDecoration(color: const Color(0xFF23B0BD)),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 55.50,
                              top: 43.50,
                              child: Text(
                                'Step By Step',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 48,
                                  fontFamily: 'Roboto',
                                  fontWeight: FontWeight.w700,
                                  height: 0.42,
                                  letterSpacing: 0.48,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 34,
                      top: 205,
                      child: Container(
                        width: 327,
                        height: 494,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 158,
                                height: 148,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF89D3DA),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(25),
                                  ),
                                ),
                                child: Stack(
                                  children: [
                                    Center(
                                      child: Icon(Icons.person,
                                          size: 100, color: const Color.fromARGB(221, 255, 255, 255)),
                                    ),
                                    Positioned(
                                      left: 41,
                                      top: 106.79,
                                      child: Text(
                                        'Usuario',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 20,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w600,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 169,
                              top: 0,
                              child: Container(
                                width: 158,
                                height: 148,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF89D3DA),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(25),
                                  ),
                                ),
                                child: Stack(
                                  children: [
                                    Center(
                                      child: Icon(Icons.medical_services,
                                          size: 80, color: const Color.fromARGB(221, 255, 255, 255)),
                                    ),
                                    Positioned(
                                      left: 32,
                                      top: 108,
                                      child: Text(
                                        'Tratamiento',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 16,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w600,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 173,
                              child: Container(
                                width: 158,
                                height: 148,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF89D3DA),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(25),
                                  ),
                                ),
                                child: Stack(
                                  children: [
                                      Center(
                                      child: Icon(Icons.people,
                                          size: 100, color: const Color.fromARGB(221, 255, 255, 255)),
                                    ),
                                    Positioned(
                                      left: 21.50,
                                      top: 103,
                                      child: Text(
                                        'Conocer gente',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 16,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w600,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 169,
                              top: 173,
                              child: Container(
                                width: 158,
                                height: 148,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF89D3DA),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(25),
                                  ),
                                ),
                                child: Stack(
                                  children: [
                                     Center(
                                      child: Icon(Icons.bar_chart,
                                          size: 100, color: const Color.fromARGB(221, 255, 255, 255)),
                                    ),
                                    Positioned(
                                      left: 34.50,
                                      top: 109,
                                      child: Text(
                                        'Progreso',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 20,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w600,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 346,
                              child: Container(
                                width: 327,
                                height: 148,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF89D3DA),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(25),
                                  ),
                                ),
                                child: Center(
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        children: [
                                          Icon(
                                            Icons.help_outline,
                                            size: 120,
                                            color: Colors.white,
                                          ),
                                          const SizedBox(width: 8), 
                                          Text(
                                            'Ayuda',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 32,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w600,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 0,
                      top: 768,
                      child: Container(
                        width: 393,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.end,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 10,
                          children: [
                            Container(
                              width: double.infinity,
                              height: 84,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0.50,
                                    child: Container(
                                      width: 393,
                                      height: 83,
                                      decoration: BoxDecoration(color: const Color(0xFFFAFAFA)),
                                    ),
                                  ),
                                  Positioned(
                                    left: 129,
                                    top: 69.50,
                                    child: Container(
                                      width: 134,
                                      height: 5,
                                      decoration: ShapeDecoration(
                                        color: Colors.black,
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 27,
                                    top: 15,
                                    child: Container(
                                      width: 32,
                                      height: 32,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFFE7E7E7),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 103,
                                    top: 15,
                                    child: Container(
                                      width: 32,
                                      height: 32,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFF08C9DB),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 179,
                                    top: 15,
                                    child: Container(
                                      width: 32,
                                      height: 32,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFFE7E7E7),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 254,
                                    top: 15,
                                    child: Container(
                                      width: 32,
                                      height: 32,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFFE7E7E7),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 330,
                                    top: 15,
                                    child: Container(
                                      width: 32,
                                      height: 32,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFFE7E7E7),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Container(
                                      width: 393,
                                      height: 0.50,
                                      decoration: BoxDecoration(color: const Color(0xFFBDC5CD)),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  
                   
                   
                    
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}