import 'package:flutter/material.dart';
import 'package:adiccion/widget/barras.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Progreso(),
        ]),
      ),
    );
  }
}

class Progreso extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 779,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFF0FFFD)),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 36,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 7,
                        top: 0,
                        child: Container(
                          width: 379,
                          height: 36,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 357,
                                top: 8,
                                child: Text(
                                  '-->',
                                  textAlign: TextAlign.right,
                                  style: TextStyle(
                                    color: const Color(0xFF81BED5),
                                    fontSize: 16,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 125,
                                top: 0,
                                child: Text(
                                  'Progreso',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 30,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 8,
                                child: Text(
                                  '<--',
                                  style: TextStyle(
                                    color: const Color(0xFF81BED5),
                                    fontSize: 16,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 47,
                child: Container(
                  width: 344,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFC5F0F4),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 47,
                child: Container(
                  width: 393,
                  padding: const EdgeInsets.symmetric(horizontal: 25),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 10,
                    children: [
                      Container(
                        width: 343,
                        height: 50,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 16,
                              top: 16,
                              child: Text(
                                'Search',
                                style: TextStyle(
                                  color: const Color(0xFF417571),
                                  fontSize: 16,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                       Frame14(),
                    ],
                  ),
                ),
               
              ),
              Positioned(
                left: 0,
                top: 380,
                child: Container(
                  width: 393,
                  padding: const EdgeInsets.symmetric(horizontal: 25),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 10,
                    children: [
                      Container(
                        width: 177,
                        height: 17,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0.50,
                              child: Container(
                                width: 16,
                                height: 16,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 16,
                                        height: 16,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF1493E1),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(
                                              width: 1,
                                              color: const Color(0xFF4B9360),
                                            ),
                                            borderRadius: BorderRadius.circular(4),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 4,
                                      top: 4,
                                      child: Container(width: 8, height: 7, child: Stack()),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 24,
                              top: 0,
                              child: SizedBox(
                                width: 154,
                                child: Text(
                                  'Objetivos',
                                  style: TextStyle(
                                    color: const Color(0xFF666666),
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 408,
                child: Container(
                  width: 393,
                  padding: const EdgeInsets.symmetric(horizontal: 25),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 10,
                    children: [
                      Container(
                        width: 177,
                        height: 17,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0.50,
                              child: Container(
                                width: 16,
                                height: 16,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 16,
                                        height: 16,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF1493E1),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(
                                              width: 1,
                                              color: const Color(0xFF4B9360),
                                            ),
                                            borderRadius: BorderRadius.circular(4),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 4,
                                      top: 4,
                                      child: Container(width: 8, height: 7, child: Stack()),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 24,
                              top: 0,
                              child: SizedBox(
                                width: 154,
                                child: Text(
                                  'Requerimientos',
                                  style: TextStyle(
                                    color: const Color(0xFF666666),
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 436,
                child: Container(
                  width: 393,
                  padding: const EdgeInsets.symmetric(horizontal: 25),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 10,
                    children: [
                      Container(
                        width: 177,
                        height: 17,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0.50,
                              child: Container(
                                width: 16,
                                height: 16,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 16,
                                        height: 16,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF1493E1),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(
                                              width: 1,
                                              color: const Color(0xFF4B9360),
                                            ),
                                            borderRadius: BorderRadius.circular(4),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 4,
                                      top: 4,
                                      child: Container(width: 8, height: 7, child: Stack()),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 24,
                              top: 0,
                              child: SizedBox(
                                width: 154,
                                child: Text(
                                  'Alcances',
                                  style: TextStyle(
                                    color: const Color(0xFF666666),
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 464,
                child: Container(
                  width: 393,
                  padding: const EdgeInsets.symmetric(horizontal: 25),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 10,
                    children: [
                      Container(
                        width: 177,
                        height: 17,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0.50,
                              child: Container(
                                width: 16,
                                height: 16,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 16,
                                        height: 16,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF1493E1),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(
                                              width: 1,
                                              color: const Color(0xFF4B9360),
                                            ),
                                            borderRadius: BorderRadius.circular(4),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 4,
                                      top: 4,
                                      child: Container(width: 8, height: 7, child: Stack()),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 24,
                              top: 0,
                              child: SizedBox(
                                width: 154,
                                child: Text(
                                  'Limites',
                                  style: TextStyle(
                                    color: const Color(0xFF666666),
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 492,
                child: Container(
                  width: 393,
                  padding: const EdgeInsets.symmetric(horizontal: 25),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 10,
                    children: [
                      Container(
                        width: 177,
                        height: 17,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0.50,
                              child: Container(
                                width: 16,
                                height: 16,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 16,
                                        height: 16,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF1493E1),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(
                                              width: 1,
                                              color: const Color(0xFF4B9360),
                                            ),
                                            borderRadius: BorderRadius.circular(4),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 4,
                                      top: 4,
                                      child: Container(width: 8, height: 7, child: Stack()),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 24,
                              top: 0,
                              child: SizedBox(
                                width: 154,
                                child: Text(
                                  'Asistencias',
                                  style: TextStyle(
                                    color: const Color(0xFF666666),
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 520,
                child: Container(
                  width: 393,
                  padding: const EdgeInsets.symmetric(horizontal: 25),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 10,
                    children: [
                      Container(
                        width: 177,
                        height: 17,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0.50,
                              child: Container(
                                width: 16,
                                height: 16,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 16,
                                        height: 16,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF1493E1),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(
                                              width: 1,
                                              color: const Color(0xFF4B9360),
                                            ),
                                            borderRadius: BorderRadius.circular(4),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 4,
                                      top: 4,
                                      child: Container(width: 8, height: 7, child: Stack()),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 24,
                              top: 0,
                              child: SizedBox(
                                width: 154,
                                child: Text(
                                  'Colaboraciones',
                                  style: TextStyle(
                                    color: const Color(0xFF666666),
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 548,
                child: Container(
                  width: 393,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 22,
                        top: 2,
                        child: Container(
                          width: 344,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFDADADA),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(25),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 194,
                        top: 2,
                        child: Container(
                          width: 172,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(25),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 68,
                        top: 17,
                        child: Text(
                          'Semanal',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 15,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 249,
                        top: 17,
                        child: Text(
                          'Mensual',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF23B0BD),
                            fontSize: 15,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 609,
                child: Container(
                  width: 393,
                  height: 77,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 28,
                        top: 13,
                        child: Container(
                          width: 328,
                          height: 77,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFF6F6F6),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(100),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 50,
                                top: 0,
                                child: Text(
                                  'First Last',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 16,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 278,
                                top: 2,
                                child: Text(
                                  '8m ago',
                                  textAlign: TextAlign.right,
                                  style: TextStyle(
                                    color: const Color(0xFFBDBDBD),
                                    fontSize: 14,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 50,
                                top: 27,
                                child: SizedBox(
                                  width: 254,
                                  child: Text(
                                    'Hell want to use your yacht, and I dont want this thing smelling like fish.',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 14,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 77,
                                child: Container(
                                  width: 328,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFE7E7E7),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 697,
                child: Container(
                  width: 393,
                  height: 80,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: double.infinity,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.end,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 10,
                          children: [
                            Container(
                              width: double.infinity,
                              height: 84,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0.50,
                                    child: Container(
                                      width: 393,
                                      height: 83,
                                      decoration: BoxDecoration(color: const Color(0xFFFAFAFA)),
                                    ),
                                  ),
                                  Positioned(
                                    left: 129,
                                    top: 69.50,
                                    child: Container(
                                      width: 134,
                                      height: 5,
                                      decoration: ShapeDecoration(
                                        color: Colors.black,
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 27,
                                    top: 15,
                                    child: Container(
                                      width: 32,
                                      height: 32,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFF08C9DB),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 103,
                                    top: 15,
                                    child: Container(
                                      width: 32,
                                      height: 32,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFFE7E7E7),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 179,
                                    top: 15,
                                    child: Container(
                                      width: 32,
                                      height: 32,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFFE7E7E7),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 254,
                                    top: 15,
                                    child: Container(
                                      width: 32,
                                      height: 32,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFFE7E7E7),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 330,
                                    top: 15,
                                    child: Container(
                                      width: 32,
                                      height: 32,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFFE7E7E7),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(100),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Container(
                                      width: 393,
                                      height: 0.50,
                                      decoration: BoxDecoration(color: const Color(0xFFBDC5CD)),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}



